#!/usr/bin/env sh
#
# This script tries to install swmfpy in the supported way (through pip).
# The swmfpy folder in share/Scripts/swmfpy is there as a bundle to SWMF and not
# to be used when using python scripts.

python3 -m pip -U --user install swmfpy || python3 -m pip -U install swmfpy || pip -U --user install swmfpy || pip -U install swmfpy
