#!/usr/bin/perl -s

my $Help = ($h or $help);
my $History = $history;

use strict;

my $swmf_software     = "git\@github.com:SWMFsoftware";
my $csem_software     = "git\@gitlab.umich.edu:csem_software";
my $solstice_software = "git\@gitlab.umich.edu:solstice-software";

# The project name should be all capitalized.
my %url = (
    "BATSRUS_GPU"        => $csem_software,
    "BATSRUS_GPU_SIMPLE" => $csem_software,
    "CIMI2"              => "git\@gitlab.umich.edu:SWMF_software",
    "LATEX"              => $csem_software,
    "VAC"                => $csem_software,
    "WSA"                => $csem_software,
    "GITM"               => "https://github.com/GITMCode",
    "VISANAMATLAB"       => "https://github.com/henry2004y",
    "BATSRUS.jl"         => "https://github.com/henry2004y",
    "PARAMINS_GEOSPACE"  => $solstice_software,
    "CME_LIST"           => $solstice_software,
    "SWMF_PLOT_GEOSPACE" => $solstice_software,
    "SUPERMAGSTATIONS"   => $solstice_software,
    );

my @repo = ("SWMF, AMPS, BATSRUS, CIMI2, FSAM, FLEKS, GITM2, MFLAMPA, PWOM ...", 
            sort keys %url);

if($Help or not @ARGV){
    print "
Clone a project from the proper git repository. 

Usage:
  gitclone [-h] [-s] [-history] REPO [flags] [DIRNAME]

-h -help      Print help message.

-history      Clone with history. If not present the --depth 1 is used

flags         Any git flag.
DIRNAME       Name of local directory (default is same as REPO)
REPO          Name of repository, including the following:\n\t\t", join("\n\t\t", @repo), "

Examples:

Clone BATSRUS repository from swmf_software with history:

   gitclone -history BATSRUS

Clone LATEX repositiry from csem_software without history into Papers/BIBTEX:

   gitclone LATEX Papers/BIBTEX

";
    exit 0;
}




my $project = $ARGV[0]; $project =~ s/\.git$//;

my $url = ($url{uc($project)} or $swmf_software);

$ARGV[0] .= " --depth 1 --no-single-branch" unless $History;

my $command = "git clone $url/".join(" ", @ARGV);

print "$command\n";
`$command`;

exit 0;
