#!/usr/bin/perl -s

my $Help = ($h or $help);
my $History = $history;

use strict;

my $mstemquda_software = 'git@github.com:MSTEM-QUDA';

# The project name should be all capitalized.
my %url = (
    "GITM"         => "https://github.com/aaronjridley",
    "MGITM"        => "https://github.com/dpawlows",
    "VISANAMATLAB" => "https://github.com/henry2004y",
    "BATSRUS.jl"   => "https://github.com/henry2004y",
    );

my @repo = ("SWMF, BATSRUS, RCM2, RBE, Ridley_serial, BATL", 
            sort keys %url);

if($Help or not @ARGV){
    print "
Clone a project from the proper git repository. 

Usage:
  githubclone [-h] [-history] REPO [flags] [DIRNAME]

-h -help      Print help message.

-history      Clone with history. If not present the --depth 1 is used

flags         Any git flag.
DIRNAME       Name of local directory (default is same as REPO)
REPO          Name of repository, including the following:\n\t\t", join("\n\t\t", @repo), "

Examples:

Clone BATSRUS repository from MSTEM-QUDA with history:

   githubclone -history BATSRUS

Clone GITM repositiry from GitHub without history into GITM_no_history:

   githubclone GITM GITM_no_history

";
    exit 0;
}

my $project = $ARGV[0]; $project =~ s/\.git$//;

my $url = ($url{uc($project)} or $mstemquda_software);

$ARGV[0] .= " --depth 1" unless $History;

my $command = "git clone $url/".join(" ", @ARGV);

print "$command\n";
`$command`;

exit 0;
